name: Call a reusable workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main



jobs:
  build_using_template:

    runs-on: windows-latest

    steps:
    - name: Set temp folder parameter
      run: echo '::set-output name=RUNNER_TEMP_BASE::green'
      id: my-temp-folder
    - name: call-workflow-passing-data
      uses: ./.github/workflows/reusableworkflowtemplate.yml
      with:
        templatebasepath: ${{ steps.my-temp-folder.outputs.RUNNER_TEMP_BASE }}
        templatefilename: 'dummydata.dat'