name: Call a reusable workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main



jobs:
  env:
  # Setting temp folder
    RUNNER_TEMP_FOLDER: $RUNNER_TEMP
    steps:
    - name: call-workflow-passing-data
      uses: ./.github/workflows/reusableworkflowtemplate.yml
      with:
        templatebasepath: ${{ env.RUNNER_TEMP_FOLDER }}
        templatefilename: 'dummydata.dat'
