name: Call a reusable workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main

env:
  # Setting temp folder
  RUNNER_TEMP_FOLDER: ${{env.RUNNER_TEMP }}

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusableworkflowtemplate.yml
    with:
      templatebasepath: ${{ env.RUNNER_TEMP_FOLDER }}
      templatefilename: 'dummydata.dat'