name: Call a reusable workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main


jobs:
  setup1:

    runs-on: windows-latest

    steps:
    - name: Set temp folder parameter
      run: echo '::set-output name=RUNNER_TEMP_BASE::${{ runner.Temp }}'
      id: my-temp-folder
    - name: Test
      run: echo ${{ runner.Temp }}


  call-workflow-passing-data:
    needs: setup1
    uses: ./.github/workflows/reusableworkflowtemplate.yml
    with:
      #templatebasepath: ${{ needs.setup1.steps.my-temp-folder.outputs.RUNNER_TEMP_BASE }}
      #templatebasepath: ${{ env.input}}
      templatebasepath:  'D:\a\_temp'
      templatefilename: 'dummydata.dat'