name: Call a reusable workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main



jobs:
  build_using_template:

    runs-on: windows-latest

    steps:
    #- uses: actions/checkout@v3    
    - name: Set temp folder parameter
      run: echo '::set-output name=RUNNER_TEMP_BASE::$Runner.Temp'
      id: my-temp-folder
    #- name: call-workflow-passing-data
    #  #uses: ./.github/workflows/reusableworkflowtemplate.yml
    #  uses: leffemail/JustForFun/.github/workflows/reusable-workflow.yml@main
    #  with:
    #    templatebasepath: ${{ steps.my-temp-folder.outputs.RUNNER_TEMP_BASE }}
    #    templatefilename: 'dummydata.dat'


  call-workflow-passing-data:
    uses: leffemail/JustForFun/.github/workflows/reusable-workflow.yml@main
    with:
      templatebasepath: ${{ steps.my-temp-folder.outputs.RUNNER_TEMP_BASE }}
      templatefilename: 'dummydata.dat'