name: Call a reusable workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusableworkflowtemplate.yml
    with:
      templatebasepath: 'd:\Temp'
    secrets:
      templatefilename: 'dummydata.dat'